version: v1alpha
      
platforms:
  '@homebot/platform-firetv':
    enable:
      - name: firetv
        type: FireTV
        params:
          name: firetv
          host: 10.8.1.159

  '@homebot/platform-darkskynet':
    enable:
      - name: weather
        type: Weather
        params:
          apiKey: YOUR_API_KEY
          defaultLocation:
            longitude: 43.2
            latitude: 18.65

  '@homebot/platform-mpd':
    enable:
      - name: mpd
        type: MPD
        params:
          address: localhost
    
  '@homebot/platform-sysinfo':
    enable:
      - name: localhost
        type: Sysinfo